name: build-all

on:
  workflow_dispatch:
    inputs:
      git-address:
        description: 'git-address'
        required: true
        default: 'https://github.com/buildroot/buildroot.git'
      branches-tags:
        description: 'branches-tags'
        required: true
        default: '2024.02.1'
      board:
        description: 'board'
        required: true
        default: 'a30'
      custom-config:
        description: 'custom-config'
        required: false
        default: 'a30_defconfig'
      build-with:
        description: 'build-with'
        required: false
        default: ''


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Clone source code
      run: |
        git clone ${{github.event.inputs.git-address}} /opt/buildroot
        cd /opt/buildroot

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install -y make gcc g++ unzip git bc python device-tree-compiler mtd-utils gcc-multilib g++-multilib

    - name: Bulid
      run: |
        mkdir /opt/firmware
        cd /opt/buildroot
        git checkout ${{github.event.inputs.branches-tags}}
        git pull origin ${{github.event.inputs.branches-tags}}

        if [ ${{github.event.inputs.custom-config}}!='' ]; then cp -f /home/runner/work/buildroot-actions/buildroot-actions/configs/${{github.event.inputs.custom-config}} configs/; fi

        CPU_N=$(getconf _NPROCESSORS_ONLN)

        echo '---start make---'
        echo 'CPU: ${CPU_N}'
        make ${{github.event.inputs.board}}_defconfig
        set -o pipefail
        if ! ( \
        make -j $CPU_N 2>&1 \
        | tee build.log \
        | grep ">>>" \
        ); then tail -n100 build.log && exit 1
        fi
        make sdk
        cp -r /opt/buildroot/output/images /opt/firmware
    - name: Archive build logs (musl)
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: /opt/buildroot/build.log

    - name : Upload buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
      uses: actions/upload-artifact@master
      with:
        name: buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
        path: /opt/firmware
        if-no-files-found: error
